# Generated by Django 6.0.1 on 2026-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name="End Date (Leave blank for 'Present')"),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name="End Date (Leave blank for 'Present')"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, verbose_name='Demo Link (Optional)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(verbose_name='Testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role / Company (Optional)'),
        ),
    ]
