# Generated by Django 6.0.1 on 2026-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-briefcase', 'Briefcase'), ('fa-solid fa-building', 'Building'), ('fa-solid fa-laptop-code', 'Laptop Code'), ('fa-solid fa-code', 'Code'), ('fa-solid fa-microchip', 'Microchip'), ('fa-solid fa-server', 'Server'), ('fa-solid fa-database', 'Database'), ('fa-solid fa-desktop', 'Desktop'), ('fa-solid fa-user-tie', 'User Tie'), ('fa-solid fa-handshake', 'Handshake'), ('fa-solid fa-chart-line', 'Chart Line'), ('fa-solid fa-pen-nib', 'Pen Nib')], help_text='Select a built-in icon', max_length=50),
        ),
        migrations.AddField(
            model_name='hobby',
            name='font_awesome_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-gamepad', 'Gamepad'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-camera', 'Camera'), ('fa-solid fa-plane', 'Plane'), ('fa-solid fa-bicycle', 'Bicycle'), ('fa-solid fa-palette', 'Palette'), ('fa-solid fa-utensils', 'Utensils'), ('fa-solid fa-film', 'Film'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-futbol', 'Soccer'), ('fa-solid fa-dumbbell', 'Dumbbell'), ('fa-solid fa-campground', 'Camping'), ('fa-solid fa-code', 'Code'), ('fa-solid fa-chess', 'Chess'), ('fa-solid fa-guitar', 'Guitar'), ('fa-solid fa-running', 'Running'), ('fa-solid fa-swimmer', 'Swimming')], help_text='Select a built-in icon (overrides custom image if set)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload custom icon/image (optional if built-in selected)', upload_to='hobbies/'),
        ),
    ]
