# Generated by Django 6.0.1 on 2026-02-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_profile_picture_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_bg_type',
            field=models.CharField(choices=[('GRADIENT', 'Gradient (Default)'), ('IMAGE', 'Static Image'), ('VIDEO', 'Video'), ('SLIDESHOW', 'Slideshow')], default='GRADIENT', max_length=20, verbose_name='Hero Background Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_overlay_opacity',
            field=models.DecimalField(decimal_places=1, default=0.5, help_text='Overlay opacity (0.0 to 1.0). Higher = darker.', max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_static_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/static/', verbose_name='Static Hero Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_video_file',
            field=models.FileField(blank=True, null=True, upload_to='hero/video/', verbose_name='Hero Video (MP4/WebM)'),
        ),
        migrations.AlterField(
            model_name='experiencetranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hobbytranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiletranslation',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='main.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
