# Generated by Django 5.2.11 on 2026-02-15 15:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models
from django.conf import settings

def forward_func(apps, schema_editor):
    Testimonial = apps.get_model('main', 'Testimonial')
    TestimonialTranslation = apps.get_model('main', 'TestimonialTranslation')
    
    for obj in Testimonial.objects.all():
        TestimonialTranslation.objects.create(
            master_id=obj.id,
            language_code=settings.LANGUAGE_CODE, # 'en' usually
            quote=obj.quote,
            role_company=obj.role_company
        )

def reverse_func(apps, schema_editor):
    Testimonial = apps.get_model('main', 'Testimonial')
    TestimonialTranslation = apps.get_model('main', 'TestimonialTranslation')
    
    for translation in TestimonialTranslation.objects.filter(language_code=settings.LANGUAGE_CODE):
        testimonial = translation.master
        testimonial.quote = translation.quote
        testimonial.role_company = translation.role_company
        testimonial.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_hero_bg_type_profile_hero_overlay_opacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('role_company', models.CharField(blank=True, max_length=100, verbose_name='Role / Company (Optional)')),
                ('quote', models.TextField(verbose_name='Testimonial')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.testimonial')),
            ],
            options={
                'verbose_name': 'testimonial Translation',
                'db_table': 'main_testimonial_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(forward_func, reverse_func),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role_company',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationtranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencetranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hobbytranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profiletranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skilltranslation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
