# Generated by Django 6.0.1 on 2026-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactmessage_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANGUAGES', 'Languages'), ('FRAMEWORKS', 'Frameworks'), ('INFRA', 'Infrastructure'), ('AI_ML', 'AI / ML'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Group this skill renders under.', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Manual sort order within the category (low numbers first).'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated — no longer displayed. Left for backwards compatibility.', null=True),
        ),
    ]
