# Generated by Django 6.0.1 on 2026-05-17 12:52

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_skill_options_skill_category_skill_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.CharField(blank=True, help_text='Free text, e.g. "November 2025" or "Fall 2025".', max_length=60)),
                ('icon_emoji', models.CharField(blank=True, help_text='Optional emoji, e.g. "🏆".', max_length=8)),
                ('order', models.IntegerField(default=0, help_text='Manual sort order (low numbers first).')),
            ],
            options={
                'verbose_name_plural': 'Recognitions',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecognitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.recognition')),
            ],
            options={
                'verbose_name': 'recognition Translation',
                'db_table': 'main_recognition_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
