# Generated by Django 6.0.1 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recognition_recognitiontranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.CharField(blank=True, help_text='Free text, e.g. "2026" or "Present". Optional.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, help_text='Free text, e.g. "2025". Optional.', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='role',
            field=models.CharField(blank=True, help_text='Optional, e.g. "Transactions Domain Lead".', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, default='', help_text='Deprecated — use Tech tags instead. Comma-separated legacy field.', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.techtag'),
        ),
    ]
