# Generated by Django 6.0.1 on 2026-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_techtag_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text="If checked, the end date shows '→ Present' automatically."),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_type',
            field=models.CharField(blank=True, choices=[('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part-time'), ('FULL_TIME', 'Full-time'), ('TUTORING', 'Tutoring'), ('RESEARCH', 'Research'), ('VOLUNTEER', 'Volunteer'), ('EDUCATION', 'Education')], help_text='Shown as a small badge next to the title.', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech_used',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='main.techtag'),
        ),
        migrations.AlterField(
            model_name='experiencetranslation',
            name='description',
            field=models.TextField(blank=True, help_text="Supports Markdown — use '- ' lines for bullet points."),
        ),
    ]
