# Generated by Django 6.0.1 on 2026-05-17 12:56

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_experience_is_current_experience_role_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, help_text='The resume PDF offered for download. Replaceable here without code changes.', upload_to='resume/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('availability_text', models.CharField(default='Available for Summer 2026 internships', help_text='Shown in the hero status badge and contact section.', max_length=120)),
                ('hero_tagline', models.CharField(blank=True, help_text='Subheadline under your name, e.g. "AI Research Intern at Polytechnique • Incoming SWE at Concordia".', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description + Open Graph description for this language.', max_length=300)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph / browser tab title. Falls back to name + role if blank.', max_length=120)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.sitesettings')),
            ],
            options={
                'verbose_name': 'Site Settings Translation',
                'db_table': 'main_sitesettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
